name: Pull Request

on:
  pull_request_target:
    types: [opened, synchronize, edited]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Install dependencies
        run: npm ci

      - name: Prebuild
        run: npm run prebuild

      - name: Create Release PR or Release
        uses: cadamsdev/lazy-release-action@242f972b19116494006f966c4d2e57ff067a4db1 # v0.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          end-commit: 8da2d3a8211a199b9dc7be9e9a41a35ad5603504
